rate: 0.11
prune_times: 12
prune_method: slim
save_dir: cibp_slim_8.255
lr: 0.001
slim_weight: 0.0001
weight_decay: 0.00001
eps: 8/255 
epochs: 300
lr_decay_milestones: [210,255]
scheduler_opts: start=16,length=121,mid=0.4
