hydra:
    lr: 0.01
    optimizer: adam
    epochs: 20
    momentum: 0.9
    decreasing_lr: 10,15

rate: 0.20
prune_times: 16
prune_method: hydra
save_dir: fgsm_hydra_8.255
eps: 8/255 
epochs: 300
lr_decay_milestones: [210,255]
scheduler_opts: start=16,length=121,mid=0.4
